services:
  postgres: # postgres service
    container_name: postgres-sql-bsn # bsn stands for book social network
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 1234:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080 # this port is to display the web app
      - 1025:1025 # the port that we need to use here in our application
  bsn-api: # a new service
    container_name: bsn-api
    image: bsn/bsn:1.0.3
#    environment: we can pass the env variables, but it isn't mandatory since we provided default values in the Dockerfile
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on: # this service won't run unless the postgres service is up and running
      - postgres
  bsn-ui:
    container_name: bsn-ui
    image: bsn/bsn-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - bsn-api

networks:
  spring-demo:
    name: spring-demo
    driver: bridge

volumes:
  postgres:
     driver: local