spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql # help jpa and hibernate to better generate the queries
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${EMAIL_HOSTNAME}
    port: 465
    username: ${EMAIL_USER_NAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enable: true
    protocol: smtp

server:
  port: 8088

# those are custom properties
application:
  security:
    jwt:
      secret-key: 4JTjE458zzhHdhllwrN3Yts10mldwieaVyTO1L4h8r4swnQkl83TPT2fODMgX4Hp
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

  mailing:
    frontend: # because it will be used from the frontend
      activation-url: http://localhost:4200/activate-account

  cors:
    origins: http://localhost:4200,http://localhost:8080

  file:
    upload:
      photos-output-path: ./uploads